Repository codesquad-member-2020/airbnb-08, pull requests merged in 2020-05, with the labels that each got.

#5 [BE] 프로젝트 빌드
  BE/.gitignore
  BE/.idea/.name
  BE/.idea/compiler.xml
  BE/.idea/jarRepositories.xml
  BE/.idea/misc.xml
  BE/.idea/vcs.xml
  BE/HELP.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/codesquad/airbnb/AirbnbApplication.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/codesquad/airbnb/AirbnbApplicationTests.java
  BE/src/test/java/com/codesquad/airbnb/ui/MainContoller.java
Labels: BE

#7 [Team] 이슈, PR 템플릿 작성
  .github/ISSUE_TEMPLATE/-be--title.md
  .github/ISSUE_TEMPLATE/-fe--title.md
  .github/ISSUE_TEMPLATE/-team--title.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Team

#11 [FE] 웹팩 환경 설정
  FE/.gitignore
  FE/babel.config.js
  FE/img.d.ts
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/index.tsx
  FE/src/test.png
  FE/tsconfig.json
  FE/webpack.config.js
  FE/webpack.dev.js
  FE/webpack.prod.js
  FE/yarn.lock
Labels: FE, Feature

#12 [BE} csv파일에서 DB로 데이터 입력
  BE/.idea/dataSources.xml
  BE/.idea/sqldialects.xml
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/src/main/resources/schema.sql
Labels: BE

#14 [FE] 웹팩 설정 추가
  FE/package-lock.json
  FE/webpack.dev.js
  FE/webpack.prod.js
Labels: FE, Feature

#15 [FE] 컴포넌트 구조- 파일 생성
  FE/src/components/CalendarModal/Calendar/Calendar.tsx
  FE/src/components/CalendarModal/CalendarModal.tsx
  FE/src/components/GuestCountModal/GuestCount/GuestCount.tsx
  FE/src/components/GuestCountModal/GuestCountModal.tsx
  FE/src/components/Main/Accommodation/Accommodation.tsx
  FE/src/components/Main/FilterButton/FilterButton.tsx
  FE/src/components/Main/Main.tsx
  FE/src/components/PriceModal/PriceModal.tsx
  FE/src/components/PriceModal/PriceRangeChart/PriceRangeChart.tsx
  FE/src/components/PriceModal/SelectedRange/SelectedRange.tsx
  FE/src/components/ReservationModal/PriceInfo/PriceInfo.tsx
  FE/src/components/ReservationModal/ReservationModal.tsx
  FE/src/components/ReservationModal/SelectedInfo/SelectedInfo.tsx
Labels: FE, Feature

#17 [FE] 메인화면 스타일 적용
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/components/Main/Accommodation/Accommodation.tsx
  FE/src/components/Main/FilterButton/FilterButton.tsx
  FE/src/components/Main/Main.tsx
  FE/src/style/theme.ts
  FE/tsconfig.json
  FE/webpack.dev.js
  FE/webpack.prod.js
Labels: FE, Feature

#20 [FE] 웹팩 common 설정 추가
  FE/package-lock.json
  FE/package.json
  FE/webpack.common.js
  FE/webpack.dev.js
  FE/webpack.prod.js
Labels: FE, Feature

#22 [BE] Main 화면 API 구현
  BE/.idea/dataSources.xml
  BE/.idea/sqldialects.xml
  BE/src/main/java/com/codesquad/airbnb/domain/dto/Budget.java
  BE/src/main/java/com/codesquad/airbnb/domain/dto/Guest.java
  BE/src/main/java/com/codesquad/airbnb/domain/dto/Main.java
  BE/src/main/java/com/codesquad/airbnb/domain/dto/Price.java
  BE/src/main/java/com/codesquad/airbnb/domain/dto/ReservationDate.java
  BE/src/main/java/com/codesquad/airbnb/domain/dto/RoomDTO.java
  BE/src/main/java/com/codesquad/airbnb/infra/config/DateTimeFormatConfiguration.java
  BE/src/main/java/com/codesquad/airbnb/infra/config/SimpleCorsFilter.java
  BE/src/main/java/com/codesquad/airbnb/infra/config/WebConfig.java
  BE/src/main/java/com/codesquad/airbnb/infra/dao/ReservationDAO.java
  BE/src/main/java/com/codesquad/airbnb/infra/dao/ReviewDAO.java
  BE/src/main/java/com/codesquad/airbnb/infra/dao/RoomDAO.java
  BE/src/main/java/com/codesquad/airbnb/infra/dao/UserDAO.java
  BE/src/main/java/com/codesquad/airbnb/infra/dao/ViewDAO.java
  BE/src/main/java/com/codesquad/airbnb/ui/MainController.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/schema.sql
Labels: BE

#21 [FE] 헤더 UI 구현
  FE/src/components/Header/Header.tsx
  FE/src/components/Main/Main.tsx
Labels: FE, Feature

#31 [FE] 달력 모달 라이브러리 적용
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/common/calendarUtil/getColor.js
  FE/src/components/CalendarModal/Calendar/Calendar.jsx
  FE/src/components/CalendarModal/Calendar/DatePicker.jsx
  FE/src/components/CalendarModal/Calendar/DatepickerContext.js
  FE/src/components/CalendarModal/Calendar/Day.jsx
  FE/src/components/CalendarModal/Calendar/Month.jsx
  FE/src/components/CalendarModal/Calendar/NavButton.jsx
  FE/src/components/CalendarModal/CalendarModal.jsx
  FE/src/components/GuestCountModal/GuestCountModal.jsx
  FE/src/components/Main/FilterButton/FilterButton.jsx
  FE/src/components/ModalButtons.jsx
  FE/src/index.jsx
  FE/src/reducers/datePickerReducer.js
  FE/src/reducers/guestCountReducer.js
  FE/src/test.png
Labels: FE, Feature

#32 [FE] 달력 (선택날짜) redux 적용하기
  FE/src/actions/actions.js
  FE/src/components/CalendarModal/Calendar/DatePicker.jsx
  FE/src/components/CalendarModal/CalendarModal.jsx
  FE/src/components/GuestCountModal/GuestCount/GuestCount.jsx
  FE/src/components/GuestCountModal/GuestCountModal.jsx
  FE/src/components/Main/FilterButton/FilterButton.jsx
  FE/src/components/Main/Main.jsx
  FE/src/index.jsx
  FE/src/reducers/datePickerReducer.js
Labels: FE, Feature

#35 [FE] 리팩토링
  FE/public/favicon.ico
  FE/public/index.html
  FE/src/actions/datePickerAction.js
  FE/src/actions/guestCountAction.js
  FE/src/components/CalendarModal/Calendar/DatePicker.jsx
  FE/src/components/CalendarModal/Calendar/Day.jsx
  FE/src/components/CalendarModal/Calendar/Month.jsx
  FE/src/components/CalendarModal/Calendar/getColor.js
  FE/src/components/CalendarModal/CalendarModal.jsx
  FE/src/components/GuestCountModal/GuestCount/GuestCount.jsx
  FE/src/components/GuestCountModal/GuestCountModal.jsx
  FE/src/components/Main/Accommodation/Accommodation.jsx
  FE/src/components/Main/FilterButton/FilterButton.jsx
  FE/src/components/Main/Main.jsx
  FE/src/components/ModalButtons.jsx
  FE/src/index.jsx
  FE/src/reducers/guestCountReducer.js
Labels: FE, enhancement

#36 [FE] 요금 모달창 만들기
  FE/package-lock.json
  FE/package.json
  FE/src/components/PriceModal/PriceModal.jsx
  FE/src/components/PriceModal/PriceRangeChart/PriceRangeChart.jsx
  FE/src/components/PriceModal/SelectedRange/SelectedRange.jsx
Labels: FE, Feature
